services:
  llama-swap:
    image: ghcr.io/mostlygeek/llama-swap:vulkan
    container_name: llama-swap
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
    volumes:
      - /opt/models:/models
      - /srv/llama-swap/config.yaml:/app/config.yaml
    networks:
      - proxynet

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - /srv/open-webui:/app/backend/data
    depends_on:
      - llama-swap
    #ports:
    #  - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    labels:
      - "traefik.http.routers.open-webui.rule=Host(`ai.home`)" 
      - "traefik.http.routers.open-webui.entrypoints=websecure"
      - "traefik.http.routers.open-webui.tls=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-middleware.redirectscheme.scheme=https"
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: proxynet
