services:
  llama-swap:
    image: ghcr.io/mostlygeek/llama-swap:vulkan
    container_name: llama-swap
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
    volumes:
      - /opt/models:/models
      - /srv/llama-swap/config.yaml:/app/config.yaml
    networks:
      - ainet

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - /srv/open-webui:/app/backend/data
    depends_on:
      - llama-swap
    #ports:
    #  - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    labels:
      - "traefik.http.routers.open-webui.rule=Host(`ai.mdelponte.com`)" 
      - "traefik.http.routers.open-webui.entrypoints=websecure"
      - "traefik.http.routers.open-webui.tls=true"
      - "traefik.http.routers.open-webui.tls.certresolver=cloudflare"
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.middlewares=http-redirect"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
    networks:
      - proxynet
      - ainet

#  open-terminal:
#    image: ghcr.io/open-webui/open-terminal:latest
#    container_name: open-terminal
#    environment:
#      - 'OPEN_TERMINAL_API_KEY=${OPEN_TERMINAL_API_KEY}'
#    # ports:
#    #   - 8000:8000
#    volumes:
#      - open-terminal:/home/user
#    networks:
#      - ainet

#  genfiles-mcp:
#    image: ghcr.io/baronco/genfilesmcp:latest
#    container_name: gen_files_mcp
#    # ports:
#    #   - 8016:8016
#    environment:
#      - REVIEWER_AI_ASSISTANT_NAME=GenFilesMCP
#      - ENABLE_CREATE_KNOWLEDGE=false
#      - OWUI_URL=http://open-webui:8080
#      - PORT=8016
#    networks:
#      - ainet

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/New_York
    restart: unless-stopped
    networks:
      - ainet

# volumes:
#   open-terminal:

networks:
  proxynet:
    external: true
    name: proxynet
  ainet:
    name: ainet
