services:
  llama-swap:
    image: ghcr.io/mostlygeek/llama-swap:vulkan
    container_name: llama-swap
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
    volumes:
      - /opt/models:/models
      - /srv/llama-swap/config.yaml:/app/config.yaml

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - /srv/open-webui:/app/backend/data
    depends_on:
      - llama-swap
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
