services:
  discord-bot:
    container_name: discord-bot
    image: ghcr.io/madelponte/discord-bot:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - ainet

networks:
  ainet:
    external: true
    name: ainet
