services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: always
    #ports:
    #    - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /srv/mealie/data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.local
    networks:
      - proxynet
    labels:
      - "traefik.http.routers.mealie.rule=Host(`mealie.home`)" 
      - "traefik.http.routers.mealie.entrypoints=websecure"
      - "traefik.http.routers.mealie.tls=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-middleware.redirectscheme.scheme=https"

networks:
  proxynet:
    external: true
    name: proxynet
