services:
  archiveTeamWarrior:
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    container_name: archiveTeamWarrior
    hostname: archiveTeamWarrior
    security_opt:
      - no-new-privileges:true
    environment:
      - HTTP_USERNAME=${USERNAME}
      - HTTP_PASSWORD=${PASSWORD}
      - SELECTED_PROJECT=auto
      - DOWNLOADER=${NICKNAME}
      - CONCURRENT_ITEMS=3
    ports:
      - "192.168.2.27:8001:8001"
    restart: always
