services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: host
    environment:
      - TZ=America/New_York
      - ALLOWED_NETWORKS=192.168.2.0/24
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/plex/config:/config
      - /srv/plex/transcode:/transcode
      - /mnt/music/:/data/music
      - /mnt/video/:/data/videos
      - /mnt/downloads/:/data/downloads
    restart: unless-stopped
