services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    environment:
      - TZ=America/New_York
      - ALLOWED_NETWORKS=192.168.2.0/24
    #ports:
    #  - 32400:32400/tcp
    #  - 3005:3005/tcp
    #  - 8324:8324/tcp
    #  - 32469:32469/tcp
    #  - 1900:1900/udp
    #  - 32410:32410/udp
    #  - 32412:32412/udp
    #  - 32413:32413/udp
    #  - 32414:32414/udp
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/plex/config:/config
      - /srv/plex/transcode:/transcode
      - /mnt/music/:/data/music
      - /mnt/video/:/data/videos
      - /mnt/torrents/:/data/torrents
    restart: unless-stopped
