services:
  handbrake:
    image: jlesage/handbrake:latest
    container_name: handbrake
    environment:
      - TZ=America/New_York
      - DARK_MODE=1
    ports:
      - "5800:5800"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/handbrake/config:/config:rw
      - /mnt/video/:/output:rw
      - /mnt/downloads/:/storage:ro
      - /mnt/downloads/autoconvert/:/watch
    restart: unless-stopped
    networks:
      - proxynet
networks:
  proxynet:
    external: true
    name: proxynet
