services:
  llama-swap:
    image: ghcr.io/mostlygeek/llama-swap:rocm
    container_name: llama-swap
    restart: unless-stopped
    env_file:
      - ./env/llama-swap.env
    security_opt:
      - seccomp:unconfined
      - no-new-privileges:true
    labels:
      - "traefik.http.routers.llama-swap.rule=Host(`api.ai.mdelponte.com`)" 
      - "traefik.http.routers.llama-swap.entrypoints=websecure"
      - "traefik.http.routers.llama-swap.tls=true"
      - "traefik.http.routers.llama-swap.tls.certresolver=cloudflare"
      - "traefik.enable=true"
      - "traefik.http.routers.llama-swap.middlewares=lan-only@file"
      - "traefik.http.services.llama-swap.loadbalancer.server.port=8080"
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
    volumes:
      - /opt/models:/models
      - /srv/llama-swap/config.yaml:/app/config.yaml:ro
    networks:
      - ainet
      - proxynet

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    env_file:
      - ./env/open-webui.env
    security_opt:
      - no-new-privileges:true
    volumes:
      - /srv/open-webui:/app/backend/data
    depends_on:
      - llama-swap
    #ports:
    #  - 3000:8080
    restart: unless-stopped
    labels:
      - "traefik.http.routers.open-webui.rule=Host(`ai.mdelponte.com`)" 
      - "traefik.http.routers.open-webui.entrypoints=websecure"
      - "traefik.http.routers.open-webui.tls=true"
      - "traefik.http.routers.open-webui.tls.certresolver=cloudflare"
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.middlewares=lan-only@file"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
    networks:
      - proxynet
      - ainet

  mcp-server:
    image: ghcr.io/madelponte/mcp-server:latest
    container_name: mcp-tools
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    env_file:
      - ./env/mcp-server.env
    #ports:
    #  - "8000:8000"
    labels:
      - "traefik.http.routers.mcp.rule=Host(`mcp.mdelponte.com`)" 
      - "traefik.http.routers.mcp.entrypoints=websecure"
      - "traefik.http.routers.mcp.tls=true"
      - "traefik.http.routers.mcp.tls.certresolver=cloudflare"
      - "traefik.enable=true"
      - "traefik.http.routers.mcp.middlewares=lan-only@file"
      - "traefik.http.services.mcp.loadbalancer.server.port=8000"
    networks:
      - ainet
      - proxynet

  tika:
    image: apache/tika:latest-full
    container_name: tika
    security_opt:
      - no-new-privileges:true
    #ports:
    #  - "9998:9998"
    restart: unless-stopped
    networks:
      - ainet

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    security_opt:
      - no-new-privileges:true
    env_file:
      - ./env/flaresolverr.env
    restart: unless-stopped
    networks:
      - ainet

networks:
  proxynet:
    external: true
    name: proxynet
  ainet:
    name: ainet
