services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /srv/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    labels:
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.mdelponte.com`)" 
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.routers.homeassistant.tls.certresolver=cloudflare"
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-middleware.redirectscheme.scheme=https"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: proxynet