services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    # Volumes store your data between container upgrades
    volumes:
      - '/srv/pihole/etc-pihole:/etc/pihole'
      - '/srv/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    networks:
      piholevlan:
        ipv4_address: 192.168.2.23

networks:
  piholevlan:
    name: piholevlan
    driver: macvlan
    driver_opts:
      parent: br0
    ipam:
      config:
        - subnet: "192.168.2.0/24"
          ip_range: "192.168.2.23/32"
          gateway: "192.168.2.1"