services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    restart: unless-stopped
    environment:
      # Traefik only needs read access to container metadata and events.
      CONTAINERS: "1"
      EVENTS: "1"
      PING: "1"
      VERSION: "1"
      POST: "0"
      LOG_LEVEL: warning
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-api
    read_only: true
    tmpfs:
      - /run
    security_opt:
      - no-new-privileges:true

  traefik:
    image: dhi.io/traefik:3
    container_name: traefik
    restart: unless-stopped
    depends_on:
      - socket-proxy
    security_opt:
      - no-new-privileges:true
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/cf_dns_api_token
      CF_ZONE_API_TOKEN_FILE: /run/secrets/cf_zone_api_token
    labels:
      # Enable self‑routing
      - "traefik.enable=true"

      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`traefik.mdelponte.com`) || Host(`traefik2.mdelponte.com`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=cloudflare"
      - "traefik.http.routers.dashboard.tls.domains[0].main=mdelponte.com"
      - "traefik.http.routers.dashboard.tls.domains[0].sans=*.mdelponte.com"
      # middlewares
      - "traefik.http.middlewares.homelab-auth.basicauth.usersfile=/run/secrets/basic_auth_users"
      - "traefik.http.routers.dashboard.middlewares=homelab-auth@docker"
      - "traefik.http.middlewares.http-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.local-whitelist.ipwhitelist.sourcerange=127.0.0.1/32, 192.168.2.0/24"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/traefik/letsencrypt:/letsencrypt
      - /srv/traefik/logs:/var/log/traefik
      - ./config:/etc/traefik:ro
    secrets:
      - cf_dns_api_token
      - cf_zone_api_token
      - basic_auth_users
    networks:
      - proxynet
      - docker-api

networks:
  proxynet:
    name: proxynet
    external: true
  docker-api:
    internal: true

secrets:
  basic_auth_users:
    file: /srv/traefik/secrets/basic_auth_users
  cf_dns_api_token:
    file: /srv/traefik/secrets/cf_dns_api_token
  cf_zone_api_token:
    file: /srv/traefik/secrets/cf_zone_api_token
