services:
  pihole:
    container_name: adguard
    image: adguard/adguardhome:latest
    volumes:
      - '/srv/adguard/work:/opt/adguardhome/work'
      - '/srv/adguard/conf:/opt/adguardhome/conf'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      piholevlan:
        ipv4_address: 192.168.2.22

networks:
  piholevlan:
    name: adguardvlan
    driver: macvlan
    driver_opts:
      parent: br0
    ipam:
      config:
        - subnet: "192.168.2.0/24"
          ip_range: "192.168.2.22/32"
          gateway: "192.168.2.1"