services:
  nginx:
    build: ./config/
    container_name: nginx
    volumes:
      - /srv/nginx/ssl:/ssl/
    ports:
      - 80:80
      - 443:443
    networks:
      - proxynet
    restart: unless-stopped
networks:
  proxynet:
    name: proxynet
    driver: bridge
