services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /srv/jackett/config:/config
    #ports:
    #  - 9117:9117
    restart: unless-stopped
    labels:
      - "traefik.http.routers.jackett.rule=Host(`jackett.mdelponte.com`)" 
      - "traefik.http.routers.jackett.entrypoints=websecure"
      - "traefik.http.routers.jackett.tls=true"
      - "traefik.http.routers.jackett.tls.certresolver=cloudflare"
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-middleware.redirectscheme.scheme=https"
    networks:
      - proxynet
      - arrs

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /srv/sonarr/config:/config
      - /mnt/media/tv:/tv
      - /mnt/media/anime:/anime
      - /mnt/media/downloads:/downloads
    #ports:
    #  - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.mdelponte.com`)" 
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=cloudflare"
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-middleware.redirectscheme.scheme=https"
    networks:
      - proxynet
      - arrs

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /srv/radarr/config:/config
      - /mnt/media/movies:/movies
      - /mnt/media/downloads:/downloads
      - /mnt/media/anime-movies:/anime-movies
    #ports:
    #  - 7878:7878
    restart: unless-stopped
    labels:
      - "traefik.http.routers.radarr.rule=Host(`radarr.mdelponte.com`)" 
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=cloudflare"
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-middleware.redirectscheme.scheme=https"
    networks:
      - proxynet
      - arrs

  #lidarr:
  #  image: lscr.io/linuxserver/lidarr:latest
  #  container_name: lidarr
  #  environment:
  #    - PUID=1001
  #    - PGID=1001
  #    - TZ=America/New_York
  #  volumes:
  #    - /srv/lidarr/config:/config
  #    - /mnt/media/music_lidarr:/music
  #    - /mnt/media/downloads:/downloads
  #  #ports:
  #  #  - 8686:8686
  #  restart: unless-stopped
  #  labels:
  #  - "traefik.http.routers.lidarr.rule=Host(`lidarr.mdelponte.com`)" 
  #  - "traefik.http.routers.lidarr.entrypoints=websecure"
  #  - "traefik.http.routers.lidarr.tls=true"
  #  - "traefik.http.routers.lidarr.tls.certresolver=cloudflare"
  #  - "traefik.enable=true"
  #  - "traefik.http.middlewares.redirect-middleware.redirectscheme.scheme=https"
  #  networks:
  #   - proxynet
  #   - arrs

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /srv/bazarr/config:/config
      - /mnt/media/movies:/movies
      - /mnt/media/tv:/tv
      - /mnt/media/anime:/anime
      - /mnt/media/anime-movies:/anime-movies
    #ports:
    #  - 6767:6767
    restart: unless-stopped
    labels:
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.mdelponte.com`)" 
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.tls.certresolver=cloudflare"
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-middleware.redirectscheme.scheme=https"
    networks:
      - proxynet
      - arrs

  unpackerr:
    image: docker.io/golift/unpackerr:latest
    container_name: unpackerr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=America/New_York
      - UN_SONARR_0_URL=${SONARR_URL}
      - UN_SONARR_0_API_KEY=${SONARR_API}
      - UN_SONARR_0_PATHS_0=/data/completed/tv
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=5m
      - UN_RADARR_0_URL=${RADARR_URL}
      - UN_RADARR_0_API_KEY=${RADARR_API}
      - UN_RADARR_0_PATHS_0=/data/completed/movies
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=5m
      - UN_LIDARR_0_URL=${LIDARR_URL}
      - UN_LIDARR_0_API_KEY=${LIDARR_API}
      - UN_LIDARR_0_PATHS_0=/data/completed/music
      - UN_LIDARR_0_PROTOCOLS=torrent
      - UN_LIDARR_0_TIMEOUT=10s
      - UN_LIDARR_0_DELETE_ORIG=false
      - UN_LIDARR_0_DELETE_DELAY=5m
    volumes:
      - /srv/unpackerr/config:/config
      - /mnt/media/downloads:/data/completed
    security_opt:
      - no-new-privileges:true
    networks:
      - arrs

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/New_York
    #ports:
    #  - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - arrs

  #nzbget:
  #  image: lscr.io/linuxserver/nzbget:latest
  #  container_name: nzbget
  #  environment:
  #    - PUID=1001
  #    - PGID=1001
  #    - TZ=America/New_York
  #  volumes:
  #    - /srv/nzbget/config:/config
  #    - /mnt/media/downloads:/downloads
  #  ports:
  #    - 6788:6789
  #  restart: unless-stopped

  #tautulli:
  #  image: lscr.io/lscr.io/linuxserver/tautulli:latest
  #  container_name: tautulli
  #  environment:
  #    - PUID=1001
  #    - PGID=1001
  #    - TZ=America/New_York
  #  volumes:
  #    - /srv/tautulli/config:/config
  #  ports:
  #    - 8181:8181
  #  restart: unless-stopped

  #overseerr:
  #  image: lscr.io/linuxserver/overseerr:latest
  #  container_name: overseerr
  #  environment:
  #    - PUID=1001
  #    - PGID=1001
  #    - TZ=America/New_York
  #  volumes:
  #    - /srv/overseer/config:/config
  #  ports:
  #    - 5055:5055
  #  restart: unless-stopped

networks:
  proxynet:
    external: true
    name: proxynet
  arrs:
    name: arrs