services:
  factorio:
    image: docker.io/factoriotools/factorio:stable
    ports:
      - "34197:34197/udp"
    volumes:
     - /srv/factorio/data:/factorio
     - /srv/factorio/server-settings.json:/factorio/config/server-settings.json
    environment:
      - INSTANCE_NAME=Marcus' Server
      - INSTANCE_DESC=idk dont break anything
    entrypoint: /bin/sh -c "exec /docker-entrypoint.sh"