services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    group_add:
      - "105"
    ports:
      - "1900:1900"
      - "7359:7359"
      - "8096:8096"
    volumes:
      - /srv/jellyfin/config:/config
      - jellyfin-cache:/cache
      - /mnt/media:/data/media
    restart: 'unless-stopped'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxynet
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    labels:
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.mdelponte.com`)" 
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-middleware.redirectscheme.scheme=https"
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: proxynet
volumes:
  jellyfin-cache:
