services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    group_add:
      - "105"
    ports:
      - "1900:1900"
      - "7359:7359"
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - /mnt/music/:/media/music:ro
      - /mnt/video/:/media/videos:ro
      - /mnt/downloads/:/media/downloads:ro
    restart: 'unless-stopped'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxynet
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
networks:
  proxynet:
    external: true
    name: proxynet