services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "1900:1900"
      - "7359:7359"
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - /mnt/music/:/media/music:ro
      - /mnt/video/:/media/videos:ro
      - /mnt/torrents/:/media/torrents:ro
    restart: 'unless-stopped'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxynet
    devices:
      - /dev/dri:/dev/dri
networks:
  proxynet:
    external: true
    name: proxynet