services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/New_York
    ports:
      - "1880:1880"
    volumes:
      - /srv/node-red:/data
      - /srv/nginx/ssl:/ssl/
