services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/New_York
    #ports:
    #  - "1880:1880"
    networks:
      - proxynet
    volumes:
      - /srv/node-red:/data
networks:
  proxynet:
    external: true
    name: proxynet
