services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=America/New_York
    ports:
      - "1880:1880"
    volumes:
      - /srv/node-red/data:/data
      - /srv/node-red/ssl:/ssl/
    restart: unless-stopped
