services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
#    ports:
#      - "9443"
    volumes:
      - /srv/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - proxynet
networks:
  proxynet:
    external: true
    name: proxynet
