services:
  unifi:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi
    network_mode: host
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - /srv/unifi/config:/config
    restart: unless-stopped

