services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      - "/srv/minecraft:/data"
    environment:
      EULA: "TRUE"
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 15
      SEED: 1756818334829674443
      LEVEL_TYPE: "minecraft:amplified"
      MOTD: "Turned up to §l§c11§r"
    restart: unless-stopped

volumes:
  mc: {}
