services:
  transmission:
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - '/mnt/media/downloads:/data/completed'
      - '/srv/transmission/config:/config'
      - '/srv/transmission/openvpn:/etc/openvpn/custom/'
    environment:
      - OPENVPN_PROVIDER=custom
      - OPENVPN_CONFIG=airvpn
      #- OPENVPN_PROVIDER=MULLVAD
      #- OPENVPN_CONFIG=us_qas
      #- OPENVPN_USERNAME=${MULLVAD_USERNAME}
      #- OPENVPN_PASSWORD=${MULLVAD_PASSWORD}
      - LOCAL_NETWORK=192.168.2.0/24
      - TZ=America/New_York
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_USERNAME}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_PASSWORD}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
    logging:
      driver: json-file
      options:
          max-size: 10m
    #ports:
    #  - 9091:9091
    image: docker.io/haugene/transmission-openvpn:edge
    container_name: transmission
    restart: unless-stopped
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    labels:
      - "traefik.http.routers.transmission.rule=Host(`transmission.mdelponte.com`)" 
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.tls=true"
      - "traefik.http.routers.transmission.tls.certresolver=cloudflare"
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.middlewares=http-redirect"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
    networks:
      - proxynet
networks:
  proxynet:
    external: true
    name: proxynet
