services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=mdelponte.duckdns.org
      - SERVERPORT=51820
      - PEERS=4
      - PEERDNS=192.168.2.1
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=192.168.2.0/24
    volumes:
      - /srv/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped