services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York #set correct timezone
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=192.168.2.22 #optional
      - ALLOWEDIPS=192.168.2.0/24 #Peer addresses allowed
      - INTERNAL_SUBNET=10.13.13.0/24 #Subnet used in VPN tunnel
      - SERVERURL=mdelponte.duckdns.org #Wireguard VPN server address
    volumes:
      - /srv/wireguard/config:/config
      - /usr/src:/usr/src # location of kernel headers
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
